#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn workspace @traveller-api/app lint-staged
yarn workspace @traveller-api/functions lint-staged
yarn workspace @traveller-api/address-fetcher lint-staged
yarn workspace @traveller-api/circle-fetcher lint-staged
